@del realm.exe
@dmd -g -odobj realm ^
include/sgogl ^
include/realm/timer ^
include/realm/sgogl_interface ^
include/realm/agent ^
include/realm/refable ^
include/realm/animation ^
include/realm/renderable ^
include/realm/ground ^
include/realm/wall ^
include/realm/rooted ^
include/realm/area ^
include/realm/grid ^
include/realm/material ^
include/realm/world ^
include/realm/sllist ^
include/realm/vector ^
include/realm/entity ^
include/realm/player ^
assets/entities/commoner/commoner ^
assets/grounds/rocky/rocky_ground ^
assets/worlds/testing_world/testing_world ^
-Iinclude lib/sgogl.lib